// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('GOOGLE_API_KEY', defaultValue: '--- IGNORE ---'),
    appId: '1:103027535175:web:ab19ee3db40995dec53062',
    messagingSenderId: '103027535175',
    projectId: 'gudang-damar-5e2b7',
    authDomain: 'gudang-damar-5e2b7.firebaseapp.com',
    storageBucket: 'gudang-damar-5e2b7.firebasestorage.app',
    measurementId: 'G-9FQBYPH1V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('GOOGLE_API_KEY', defaultValue: '--- IGNORE ---'),
    appId: '1:103027535175:android:81e1f1d531147017c53062',
    messagingSenderId: '103027535175',
    projectId: 'gudang-damar-5e2b7',
    storageBucket: 'gudang-damar-5e2b7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: const String.fromEnvironment('GOOGLE_API_KEY', defaultValue: '--- IGNORE ---'),
    appId: '1:103027535175:web:f66a34dd4d81dcccc53062',
    messagingSenderId: '103027535175',
    projectId: 'gudang-damar-5e2b7',
    authDomain: 'gudang-damar-5e2b7.firebaseapp.com',
    storageBucket: 'gudang-damar-5e2b7.firebasestorage.app',
    measurementId: 'G-WGFH52EG58',
  );
}
